version: '2'
services:
    intranet-app:
        image: intranet
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://intranet-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Intranet
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    intranet-mongodb:
        extends:
            file: mongodb.yml
            service: intranet-mongodb
